version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'deps'
      include: 'scope'
    open-pull-requests-limit: 5
