name: Testing
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Type checking
        run: npm run type-check --if-present

      - name: Lint check
        run: npm run lint --if-present

      - name: Run unit tests
        run: npm run test:unit:test --if-present

      - name: Run e2e tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build --if-present
          start: npm run preview --if-present
          wait-on: http://localhost:4173
          command: npm run test:e2e:test --if-present
